### ISSUE TITLE
zigbee2mqtt states, ignoring linkquality

### ISSUE THREAD

**Issue by Mirarkitty** [oerkel47/OctoPrint-PSUControl-MQTT#4]
While setting the state should be fine with z2m, getting the state is trickier:

heather% mosquitto_sub -v -h 172.16.3.5 -t 'zigbee2mqtt3/0xa4c138a52ead9193'      
zigbee2mqtt3/0xa4c138a52ead9193 {"linkquality":87,"state":"OFF"}
zigbee2mqtt3/0xa4c138a52ead9193 {"linkquality":90,"state":"OFF"}

can the matching string be a regexp or a wildcard to support this kind of data? 
Subscribing to ".../state" does not seem to read anything from MQTT.

**Comment by oerkel47** [comment]
Hey. If I understand correctly there is no dedicated state topic in your setup but only the "root" device with JSON entries.

Try the following sense settings:

state topic 
>  zigbee2mqtt3/0xa4c138a52ead9193

on and off response to
> {"state":"ON"}
> {"state":"OFF"}

**Comment by Mirarkitty** [comment]
It will ignore the other entries in the JSON dataset? What's the easiest way to see if this works correctly?

The "toggle PSU" icon does not update from switch state change at least...

Edit: Yes, it worked. I had to turn it off yesterday (something caused the polling(?) to make octoprint hang for a long time between every gcode sent, but since I can't find the actual cause I didn't make a ticket)

**Comment by oerkel47** [comment]
>It will ignore the other entries in the JSON dataset? What's the easiest way to see if this works correctly?

Yes should work that way. You can also set the octoprint logs for this plugin to debug, it should give plenty of information in the logs then.

>Edit: Yes, it worked.

Nice, glad to hear!

**Comment by Mirarkitty** [comment]
Thanks!
